general:
  ieeeAddr: '0x7423258'
  model: respeaker_4mic
mqtt:
  broker: 192.168.1.111
  password: qwer1234
  username: miranda
speechcontrol:
  snowboy_hotword: miranda.pmdl
  snowboy_pause: False
  snowboy_sensitivity: 60
  snowboy_timeout: 5
  speech_recognition_provider: Wit.ai
  speech_recognition_provider_key: RO4RYHEPLI35FWE3AI2LFVGZDRMIP7UH
  speech_recognition_provider_username: null
