general:
  model: hifiberry_amp2  
  current_interface: multiroom
  soundcard_number: 1
  current_volume: '158'
  ieeeAddr: '0x21008'
mqtt:
  broker: 192.168.1.111
  password: qwer1234
  username: miranda
